## ======================================================================
##   ____ ____  ____  ____     ____                         
##  / ___|  _ \|  _ \| __ )   / ___|_   _ _ __  _ __  _   _ 
## | |  _| |_) | | | |  _ \  | |  _| | | | '_ \| '_ \| | | |
## | |_| |  __/| |_| | |_) | | |_| | |_| | | | | | | | |_| |
##  \____|_|   |____/|____/   \____|\__,_|_| |_|_| |_|\__, |
##                                                    |___/ 
## ----------------------------------------------------------------------
## Travis CI build script for GPDB Open Source Project.
## 
## Reference:
##   o Travis CI Docs: http://docs.travis-ci.com
## ----------------------------------------------------------------------
##
## This project builds the core Greenplum Database Open Source
## project.
##
## ======================================================================

os:
  - linux

language: c
sudo: false

cache: ccache
git:
  submodules: false

addons:
  apt:
    packages:
    - libevent-dev
    - libapr1-dev

matrix:
    include:
        - stage: test
        - stage: check-format
          os: linux
          dist: bionic
          addons:
            apt:
              sources:
                - *common_sources
                - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
                  key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
              packages:
                - clang-format-10
                - parallel
          before_install: ~
          install: ~
          before_script: ~
          after_script: ~
          script:
            - env CLANG_FORMAT=clang-format-10 src/tools/fmt gen
            - git diff --exit-code
            - env CLANG_FORMAT=clang-format-10 src/tools/fmt chk

stages:
  - check-format
  - test

## ----------------------------------------------------------------------
## Build tools
## ----------------------------------------------------------------------

compiler:
  - gcc

python:
  - "2.7"

## ----------------------------------------------------------------------
## Install supporting Python modules
## ----------------------------------------------------------------------

install:
  - pip install --user --upgrade pip
  - pip install --user "pyopenssl>=19.0.0"
  - pip install --user --pre psutil
  - pip install --user lockfile
  - pip install --user paramiko
  - pip install --user setuptools

## ----------------------------------------------------------------------
## Perform build:
##   GPDB
##   gpmapreduce
##   orafce
##   gpfdist
## ----------------------------------------------------------------------

script:
  - cd ${TRAVIS_BUILD_DIR}
  - ./configure --with-openssl --with-ldap --with-libcurl --prefix=${TRAVIS_BUILD_DIR}/gpsql --disable-orca --disable-gpcloud --enable-pxf

  - make
  - make install
  - source ${TRAVIS_BUILD_DIR}/gpsql/greenplum_path.sh
  - cd ${TRAVIS_BUILD_DIR}/gpAux/extensions/orafce
  - make install USE_PGXS=1
  - cd ${TRAVIS_BUILD_DIR}/gpAux/extensions/gpmapreduce
  - make install
  - postgres --version
  - initdb --version
  - createdb --version
  - psql --version
  - gpssh --version
  - gpmapreduce --version
  - gpfdist --version

## ----------------------------------------------------------------------
## Notification
## ----------------------------------------------------------------------
notifications:
  email:
    recipients:
      - releng@pivotal.io
    on_success: change
    on_failure: always

after_script: ccache -s
