---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotaldata/sles-gpdb-dev
    tag: 11-beta

inputs:
- name: gpdb_src
- name: gpaddon_src
- name: gpAux_ext
- name: gphdfs_dist


outputs:
- name: gpdb_artifacts

run:
  path: gpdb_src/concourse/scripts/compile_gpdb.bash

params:
  TARGET_OS:
  TARGET_OS_VERSION:
  BLD_TARGETS:
  OUTPUT_ARTIFACT_DIR: gpdb_artifacts
  CONFIGURE_FLAGS:
