platform: linux
image_resource:
  type: docker-image
inputs:
  - name: gpdb_src
  - name: gpaddon_src
  - name: gpAux_ext
  - name: gphdfs_dist

outputs:
  - name: gpdb_artifacts
run:
  path: gpdb_src/concourse/scripts/compile_gpdb.bash
params:
  TARGET_OS:
  TARGET_OS_VERSION:
  BLD_TARGETS:
  OUTPUT_ARTIFACT_DIR: gpdb_artifacts
  CONFIGURE_FLAGS:
