platform: linux
image_resource:
  type: docker-image
inputs:
  - name: gpdb_src
  - name: deb_package
outputs:
params:
  MAKE_TEST_COMMAND: ""
  CONFIGURE_FLAGS: ""
  DEBIAN_PACKAGE:
run:
  path: gpdb_src/concourse/scripts/ic_gpdb_ubuntu.bash
